default: build
build: lab3a.cpp
	g++ EXT2_info.cpp lab3a.cpp -o lab3a
debug:
	g++ -g EXT2_info.cpp lab3a.cpp -o lab3a
clean:
	rm -rf lab3a
dist:
	tar -czvf lab3a-904606576.tar.gz EXT2_info.cpp lab3a.cpp EXT2_info.h Ext_fs.h Makefile begin.sh ext2_fs.h lab3a.h README
