#NAME: Shaan Mathur
#EMAIL: shaankaranmathur97@gmail.com
#ID: 904606576

default: lab1a.c
	gcc -o lab1a lab1a.c

clean:
	rm -f lab1a-904606576.tar.gz lab1a

dist:
	tar -czf lab1a-904606576.tar.gz lab1a.c README Makefile
