# NAME: SHAAN MATHUR
# UID: 904606576
# EMAIL: SHAANKARANMATHUR@GMAIL.COM

default: lab0.c
	gcc -g lab0.c -o lab0
dist:
	tar -czf lab0-904606576.tar.gz lab0.c Makefile backtrace.png breakpoint.png README smoke_test.sh
clean:
	rm lab0 lab0-904606576.tar.gz
check:
	gcc -g lab0.c -o lab0
	./smoke_test.sh

